### ISSUE TITLE
Language Switcher not work

### ISSUE THREAD

**Issue by abuvanth** [Ezhil-Language-Foundation/tamilpesu_us#1]
https://github.com/Ezhil-Language-Foundation/tamilpesu_us/blob/f4c313a9ba720e3369dddddea887113bb8f6d694/opentamilweb/urls.py#L22
Why did You disable language switcher ?

**Comment by arcturusannamalai** [comment]
There are issues in my setup so we are showing Tamil interface directly.

**Comment by arcturusannamalai** [comment]
Resolved https://github.com/Ezhil-Language-Foundation/tamilpesu_us/commit/6fdd4aabc4f7166a3e76092b462ddd5a55f5e784
