### ISSUE TITLE
Package App as Docker Images

### ISSUE THREAD

**Issue by ssurenr** [Ezhil-Language-Foundation/tamilpesu_us#3]
Produce docker images from the app so that it can be packaged and run on cloud environments easily.

**Comment by ssurenr** [comment]
@arcturusannamalai How are you loading static files in the server?

**Comment by arcturusannamalai** [comment]
From disk. /static/ like folder. Full site package is in repo https://github.com/Ezhil-Language-Foundation/tamilpesu_us (slightly old, but same organization)
